version: '3.8'

services:
  postgres:
    container_name: handle-db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: handle
#      PGDATA: /data/postgres
#    volumes:
#      - ./data/pg:/data/postgres